[[hobby]]
Hobby
-----

A professional way to create http://rack.github.io/[Rack]-based
applications.

[[installation]]
Installation
~~~~~~~~~~~~

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'hobby'
# or this if you want to use hobby master
# gem 'hobby', github: 'ch1c0t/hobby'
----

And then execute:

[source,bash]
----
$ bundle
----

Or install it yourself as:

[source,bash]
----
$ gem install hobby
----

[[introduction]]
== Introduction

Hobby features a Sinatra-like DSL, but in contrast to Sinatra,
Hobby applications behave like usual Ruby classes.

To create a Hobby application, you create a class and include `Hobby` in it.
For example:

[source,ruby]
----
class C
  include Hobby

  get("/hello") {
    "Hello, world."
  }
end
----

Then, you can create an instance of `C` with

[source,ruby]
----
C.new
----

which will return a Rack application(an object which complies to 
http://rubydoc.info/github/rack/rack/master/file/SPEC[Rack SPEC]).

You can set some state in `#initialize` and then use it in the route's action:

[source,ruby]
----
class C
  include Hobby

  def initialize name
    @name = name
  end

  get("/hello") {
    "Hello, #{@name}."
  }
end
----

To run an application, you can put it into `config.ru`:

[source,ruby]
----
run C.new 'Hobby'
----

and then use `rackup`:

[source,bash]
----
$ rackup
----

Or, if you are using Rails, you can mount it in `config/routes.rb` with:
[source,ruby]
----
mount C.new('Hobby') => '/some_path'
----

[[features]]
Features
~~~~~~~~

* DSL inspired by http://www.sinatrarb.com/[Sinatra].
* https://github.com/luislavena/bench-micro[Speed].
* Extensible with standard ruby classes and modules, with no extra
logic. See https://github.com/ch1c0t/hobby-auth[hobby-auth] and
https://github.com/ch1c0t/hobby-json[hobby-json].
* Zero configuration.

[[philosophy]]
Philosophy
~~~~~~~~~~

* http://en.wikipedia.org/wiki/Don't_repeat_yourself[Don't repeat
yourself]
* Encourages the understanding and use of http://rack.github.io/[Rack]
and its extensions instead of providing such functionality.

[[usage]]
Usage
~~~~~

[[routes]]
Routes
^^^^^^

Every route is composed of a verb, a path (optional) and an
action(passed as a block). When an incoming request matches a route, the
action is executed and a response is sent back to the client. The return
value of the action will be the `body` of the response.

See an example:

[source,ruby]
----
class App < Hobbit::Base
  get '/' do
    # ...
  end

  post '/' do
    # ...
  end

  put '/' do
    # ...
  end

  patch '/' do
    # ...
  end

  delete '/' do
    # ...
  end

  options '/' do
    # ...
  end
end
----

When a route gets called you have this methods available:

* `env`: The Rack environment.
* `request`: a `Rack::Request` instance.
* `response`: a `Rack::Response` instance.

And any other method defined in your application.

[[available-methods]]
Available methods
+++++++++++++++++

* `delete`
* `get`
* `head`
* `options`
* `patch`
* `post`
* `put`

*Note*: Since most browsers don't support methods other than *GET* and
*POST* you must use the `Rack::MethodOverride` middleware. (See
https://github.com/rack/rack/blob/master/lib/rack/methodoverride.rb[Rack::MethodOverride]).

[[routes-with-variables]]
Routes with variables
+++++++++++++++++++++

[source,ruby]
----
require 'hobby'

class App
  include Hobby
  # matches both /hi/hobbit and /hi/patricio
  get '/hi/:name' do
    "Hello #{my[:name]}"
  end
end
----

[[redirecting]]
Redirecting
+++++++++++

If you look at Hobby implementation, you may notice that there is no
`redirect` method (or similar). This is because such functionality is
provided by
https://github.com/rack/rack/blob/master/lib/rack/response.rb[Rack::Response]
and for now we http://en.wikipedia.org/wiki/Don't_repeat_yourself[don't
wan't to repeat ourselves] (obviously you can create an extension!). So,
if you want to redirect to another route, do it like this:

[source,ruby]
----
require 'hobby'

class App
  include Hobby

  get '/' do
    response.redirect '/hi'
  end

  get '/hi' do
    'Hello World!'
  end
end
----

[[halting]]
Halting
+++++++

To immediately stop a request within route you can use `throw :halt`.

[source,ruby]
----
require 'hobby'

class App < Hobbit::Base
  use Rack::Session::Cookie, secret: SecureRandom.hex(64)

  def session
    env['rack.session']
  end

  get '/' do
    response.status = 401
    throw :halt, response.finish
  end
end
----

[[built-on-top-of-rack]]
Built on top of rack
^^^^^^^^^^^^^^^^^^^^

Each Hobby application is a Rack stack (See this
http://m.onkey.org/ruby-on-rack-2-the-builder[blog post] for more
information).

[[mapping-applications]]
Mapping applications
++++++++++++++++++++

You can mount any Rack application to the stack by using the `map` class
method:

[source,ruby]
----
require 'hobby'

class InnerApp
  include Hobby

  # gets called when path_info = '/inner'
  get do
    'Hello InnerApp!'
  end
end

class App
  include Hobby

  map('/inner') { run InnerApp.new }

  get '/' do
    'Hello App!'
  end
end
----

[[using-middleware]]
Using middleware
++++++++++++++++

You can add any Rack middleware to the stack by using the `use` class
method:

[source,ruby]
----
require 'hobby'

class App
  include Hobby

  use Rack::Session::Cookie, secret: SecureRandom.hex(64)
  use Rack::ShowExceptions

  def session
    env['rack.session']
  end

  get '/' do
    session[:name] = 'hobbit'
  end

  # more routes...
end

run App.new
----

[[security]]
Security
^^^^^^^^

By default, Hobbit (nor Rack) comes without any protection against web
attacks. The use of
https://github.com/rkh/rack-protection[rack-protection] is highly
recommended:

[source,ruby]
----
require 'hobby'
require 'rack/protection'
require 'securerandom'

class App
  include Hobby

  use Rack::Session::Cookie, secret: SecureRandom.hex(64)
  use Rack::Protection

  get '/' do
    'Hello World!'
  end
end
----

See the https://github.com/rkh/rack-protection[rack-protection]
documentation for futher information.

[[testing]]
Testing
^^^^^^^

https://github.com/brynary/rack-test[rack-test] is highly recommended.
See an example:

In `app.rb`:

[source,ruby]
----
require 'hobbit'

class App
  include Hobby

  get '/' do
    'Hello World!'
  end
end
----

In `app_spec.rb`:

[source,ruby]
----
require 'minitest/autorun'
# imagine that app.rb and app_spec.rb are stored in the same directory
require 'app'

describe App do
  include Rack::Test::Methods

  def app
    App.new
  end

  describe 'GET /' do
    it 'must be ok' do
      get '/'
      last_response.must_be :ok?
      last_response.body.must_match /Hello World!/
    end
  end
end
----

See the https://github.com/brynary/rack-test[rack-test] documentation
for futher information.

[[extensions]]
Extensions
^^^^^^^^^^

You can extend Hobbit by creating standard ruby modules. See an example:

[source,ruby]
----
module MyExtension
  def do_something
    # do something
  end
end

class App
  include Hobby
  include MyExtension

  get '/' do
    do_something
    'Hello World!'
  end
end
----

[[available-extensions]]
Available extensions
++++++++++++++++++++

* https://github.com/ch1c0t/hobby-auth[hobby-auth]: User authorization.
* https://github.com/ch1c0t/hobby-json[hobby-json]: JSON requests and
responses.

[[community]]
Community
~~~~~~~~~

* https://github.com/patriciomacadden/hobbit/wiki[Wiki]: Guides, how-tos
and recipes
* IRC: irc://chat.freenode.net/#hobbitrb[#hobbitrb] on
http://freenode.net

[[contributing]]
Contributing
~~~~~~~~~~~~

1.  Fork it
2.  Create your feature branch (`git checkout -b my-new-feature`)
3.  Commit your changes (`git commit -am 'Add some feature'`)
4.  Push to the branch (`git push origin my-new-feature`)
5.  Create new Pull Request

[[license]]
License
~~~~~~~

See the https://github.com/ch1c0t/hobby/blob/master/LICENSE[LICENSE].
