[[installation]]
== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'hobby'
# or this if you want to use hobby master
# gem 'hobby', github: 'ch1c0t/hobby'
----

And then execute:

[source,bash]
----
$ bundle
----

Or install it yourself as:

[source,bash]
----
$ gem install hobby
----

[[introduction]]
== Introduction

Hobby features a Sinatra-like DSL, but in contrast to Sinatra,
Hobby applications behave like usual Ruby classes.

To create a Hobby application, you create a class and include `Hobby` in it.
For example:

[source,ruby]
----
require 'hobby'

class C
  include Hobby

  get "/hello" do
    "Hello, world."
  end
end
----

Then, you can create an instance of `C` with

[source,ruby]
----
C.new
----

which will return a Rack application(an object which complies to 
http://rubydoc.info/github/rack/rack/master/file/SPEC[Rack SPEC]).

Because a Hobby application is just a Ruby class,
you can do with it pretty much anything
you would expect to be able to do with a Ruby class.

[[using-initialize]]
=== Using #initialize

You can set some state in `#initialize` and then use it in the route's action:

[source,ruby]
----
class C
  include Hobby

  def initialize name
    @name = name
  end

  get "/hello" do
    "Hello, #{@name}."
  end
end
----

[[using-intance-methods]]
=== Using instance methods
[source,ruby]
----
class C
  include Hobby

  def initialize name
    @name = name
  end

  def name
    @name.upcase
  end

  get "/hello" do
    "Hello, #{name}."
  end
end
----

[[how-to-run]]
=== How to run
To run an application, you can put it into `config.ru`:

[source,ruby]
----
run C.new 'Hobby'
----

and then use `rackup`:

[source,bash]
----
$ rackup
----

Or, if you are using Rails, you can mount it in `config/routes.rb` with:
[source,ruby]
----
mount C.new('Hobby') => '/some_path'
----

[[routes]]
== Routes

For common HTTP verbs, Hobby provides the route definers(methods named accordingly):

[source,ruby]
----
class App
  include Hobby

  get { 'Some string.' }
  post { 'Some string.' }
  put { 'Some string.' }
  patch { 'Some string.' }
  delete { 'Some string.' }
  # TODO: find a good example for `options`
end
----

A definer should be called with a path(optional) and an action(passed as a block).

Calling a definer has a side effect of defining a route in the router.
When an incoming request matches a route,
the action is executed and a response is sent back to the client.
The return value of the action will be the `body` of the response.

=== Default route

If a path was omitted
[source,ruby]
----
get do
  'The body returned to the HTTP client making the request.'
end
----

the action is attached to the root route, like if
[source,ruby]
----
get '/' do
  'The body returned to the HTTP client making the request.'
end
----

were called.

=== Route params

Can be accessed with `route.params` (or a shortcut `my`):

[source,ruby]
----
# will match '/index', '/hobby', '/purpose', etc.
get '/:name' do
  route.params[:name]
end

# will match '/index.css', '/index.js', etc.
get '/:name.:ext' do
  "The name is #{my[:name]} and the ext is #{my[:ext]}."
end
----

[[default-methods]]
== Default methods

The following methods are predefined:

* `env`: a `Hash`, http://www.rubydoc.info/github/rack/rack/master/file/SPEC#The_Environment[a Rack environment].
* `request`: a http://www.rubydoc.info/gems/rack/Rack/Request[`Rack::Request`].
* `response`: a http://www.rubydoc.info/gems/rack/Rack/Response[`Rack::Response`].
* `route`: a `Hobby::Router::Route`, the currently executing route.
* `route.params`, or a shortcut `my`: a `Hash` which stores route params. See <<route-params>> for a usage example.
* `halt`: returns the `response` immediately. See <<halting>> for a usage example.

[[halting]]
=== Halting

[source,ruby]
----
class App
  include Hobby

  use Rack::Session::Cookie, secret: SecureRandom.hex(64)

  def session
    env['rack.session']
  end

  get '/' do
    response.status = 401
    halt
    'This line is never going to be returned.'
  end
end
----

[[extensions]]
== Extensions

You can extend Hobby with usual modules:

[source,ruby]
----
module MyExtension
  def do_something
    # do something
  end
end

class App
  include Hobby
  include MyExtension

  get '/' do
    do_something
    'Hello World!'
  end
end
----

[[available-extensions]]
=== Available extensions

* https://github.com/ch1c0t/hobby-json[hobby-json]: JSON requests and responses.
* https://github.com/ch1c0t/hobby-auth[hobby-auth]: User authorization.


[[using-rack-builder]]
== Using Rack::Builder

You can use `map` and `use` from http://www.rubydoc.info/gems/rack/Rack/Builder[Rack::Builder].

[[mapping-applications]]
=== Mapping applications

You can mount any Rack application to a Hobby application with `map`.
Here is an example of mounting the application from <<using-initialize>>
to '/anatoly' and '/patricio' routes:

[source,ruby]
----
class App
  include Hobby

  map '/anatoly', C.new('Anatoly')
  map '/patricio', C.new('Patricio')

  get '/' do
    'Mapping app.'
  end
end
----

[[using-middleware]]
=== Using middleware

You can use any Rack middleware with `use`:

[source,ruby]
----
class App
  include Hobby

  use Rack::Session::Cookie, secret: SecureRandom.hex(64)
  use Rack::ShowExceptions

  def session
    env['rack.session']
  end

  get '/' do
    session[:name] = 'username'
  end
end
----

== Custom components

Hobby was designed to be very modular.
Many components of an application can be customized or replaced.

[source,ruby]
----
class App
  include Hobby

  self.router   = custom_router
  self.request  = custom_request
  self.response = custom_response
end
----

TODO: document the API which is expected from each of these components
and provide usage examples.

== Development

To run the specs:

[source,bash]
----
bundle exec rspec
----

To perform mutation analysis:

[source,bash]
----
bundle exec mutant --use rspec 'Hobby*'
----
